### ISSUE TITLE
Pyqt5 issue

### ISSUE THREAD

**Issue by vmnog** [ionicc/Youtube-mp3-downloader-light#35]
When I try:
`suryan@suryan-desktop:~/Desktop/Youtube-mp3-downloader-light-master$ python ui.py `

I recieve:
```

Traceback (most recent call last):
  File "ui.py", line 1, in <module>
    from PyQt5.QtGui import QGuiApplication
ImportError: No module named PyQt5.QtGui

```

I installed pyqt5 but it does not work as well...

**Comment by ionicc** [comment]
Yes, it Seems like Qt.Gui is deprecated or needs to paid for. A revamp on the GUI using some other library would be great! 😄
